inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'bin/**'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/**/*'
    - 'spec/*'
    - 'app/helpers/sessions_helper.rb'
    - 'app/models/user.rb'
    - 'spec/support/test_helper.rb'

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Layout/FirstHashElementLineBreak:
  Enabled: false

Airbnb/OptArgParameters:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Layout/LineLength:
  Max: 200

Rails/HelperInstanceVariable:
  Enabled: false #インスタンス変数をhelperで利用できる様に許可